// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SIGMA2_Proto.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Logical node identity. Mirrors SIGMA2::NodeID in SIGMA2.hpp. 0 = unknown for
/// a source, broadcast for a destination.
nonisolated enum SG2NodeId: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case nodeUndefined // = 0
  case nodeNoseCone // = 1
  case nodePayload // = 2
  case nodeEbay // = 3
  case nodeAds // = 4
  case nodeAntennaTracker // = 5
  case nodeStationaryGs // = 6
  case nodeMobileNode1 // = 7
  case nodeMobileNode2 // = 8
  case nodeMobileNode3 // = 9
  case nodeMobileNode4 // = 10

  /// rocket-cam Pico W flight camera controller
  case nodeRocketCam // = 11
  case UNRECOGNIZED(Int)

  init() {
    self = .nodeUndefined
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .nodeUndefined
    case 1: self = .nodeNoseCone
    case 2: self = .nodePayload
    case 3: self = .nodeEbay
    case 4: self = .nodeAds
    case 5: self = .nodeAntennaTracker
    case 6: self = .nodeStationaryGs
    case 7: self = .nodeMobileNode1
    case 8: self = .nodeMobileNode2
    case 9: self = .nodeMobileNode3
    case 10: self = .nodeMobileNode4
    case 11: self = .nodeRocketCam
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .nodeUndefined: return 0
    case .nodeNoseCone: return 1
    case .nodePayload: return 2
    case .nodeEbay: return 3
    case .nodeAds: return 4
    case .nodeAntennaTracker: return 5
    case .nodeStationaryGs: return 6
    case .nodeMobileNode1: return 7
    case .nodeMobileNode2: return 8
    case .nodeMobileNode3: return 9
    case .nodeMobileNode4: return 10
    case .nodeRocketCam: return 11
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [SG2NodeId] = [
    .nodeUndefined,
    .nodeNoseCone,
    .nodePayload,
    .nodeEbay,
    .nodeAds,
    .nodeAntennaTracker,
    .nodeStationaryGs,
    .nodeMobileNode1,
    .nodeMobileNode2,
    .nodeMobileNode3,
    .nodeMobileNode4,
    .nodeRocketCam,
  ]

}

/// Flight state. Superset of pins.hpp::state_t (rocket-cam) and the SIGMA2.hpp
/// FLIGHT_STATE enum.
nonisolated enum SG2FlightState: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case fsUnknown // = 0
  case fsPad // = 1
  case fsBoost // = 2
  case fsCoast // = 3
  case fsApogee // = 4
  case fsRecovery // = 5
  case fsLanded // = 6
  case UNRECOGNIZED(Int)

  init() {
    self = .fsUnknown
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .fsUnknown
    case 1: self = .fsPad
    case 2: self = .fsBoost
    case 3: self = .fsCoast
    case 4: self = .fsApogee
    case 5: self = .fsRecovery
    case 6: self = .fsLanded
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .fsUnknown: return 0
    case .fsPad: return 1
    case .fsBoost: return 2
    case .fsCoast: return 3
    case .fsApogee: return 4
    case .fsRecovery: return 5
    case .fsLanded: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [SG2FlightState] = [
    .fsUnknown,
    .fsPad,
    .fsBoost,
    .fsCoast,
    .fsApogee,
    .fsRecovery,
    .fsLanded,
  ]

}

/// RushFPV 3.3 GHz band. Values match pins.hpp::VtxBand.
nonisolated enum SG2VtxBand: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// 3G3 BAND A: 3330-3470 MHz
  case a // = 0

  /// 3G3 BAND B: 3170-3310 MHz
  case b // = 1
  case UNRECOGNIZED(Int)

  init() {
    self = .a
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .a
    case 1: self = .b
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .a: return 0
    case .b: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [SG2VtxBand] = [
    .a,
    .b,
  ]

}

/// VTX power level. Order and values match pins.hpp::VtxPower so the firmware can
/// cast directly to VtxPower and resolve with vtx_power_mw().
nonisolated enum SG2VtxPowerLevel: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  ///   ~0 mW (pit mode / RF off)
  case vtxPit // = 0

  ///   25 mW
  case vtx25Mw // = 1

  ///  200 mW
  case vtx200Mw // = 2

  /// 1000 mW
  case vtx1000Mw // = 3

  /// 4000 mW (max)
  case vtx4000Mw // = 4
  case UNRECOGNIZED(Int)

  init() {
    self = .vtxPit
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .vtxPit
    case 1: self = .vtx25Mw
    case 2: self = .vtx200Mw
    case 3: self = .vtx1000Mw
    case 4: self = .vtx4000Mw
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .vtxPit: return 0
    case .vtx25Mw: return 1
    case .vtx200Mw: return 2
    case .vtx1000Mw: return 3
    case .vtx4000Mw: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [SG2VtxPowerLevel] = [
    .vtxPit,
    .vtx25Mw,
    .vtx200Mw,
    .vtx1000Mw,
    .vtx4000Mw,
  ]

}

/// Phone -> camera. Every field is `optional` so the device applies only the
/// fields the sender actually set (proto3 optional => nanopb has_ flags). If both
/// band/channel and freq_mhz are present, freq_mhz wins.
nonisolated struct SG2CameraCommand: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// band for band+channel selection
  var band: SG2VtxBand {
    get {_band ?? .a}
    set {_band = newValue}
  }
  /// Returns true if `band` has been explicitly set.
  var hasBand: Bool {self._band != nil}
  /// Clears the value of `band`. Subsequent reads from it will return its default value.
  mutating func clearBand() {self._band = nil}

  /// channel 1..8 (1-based, like the console)
  var channel: UInt32 {
    get {_channel ?? 0}
    set {_channel = newValue}
  }
  /// Returns true if `channel` has been explicitly set.
  var hasChannel: Bool {self._channel != nil}
  /// Clears the value of `channel`. Subsequent reads from it will return its default value.
  mutating func clearChannel() {self._channel = nil}

  /// explicit frequency override in MHz
  var freqMhz: UInt32 {
    get {_freqMhz ?? 0}
    set {_freqMhz = newValue}
  }
  /// Returns true if `freqMhz` has been explicitly set.
  var hasFreqMhz: Bool {self._freqMhz != nil}
  /// Clears the value of `freqMhz`. Subsequent reads from it will return its default value.
  mutating func clearFreqMhz() {self._freqMhz = nil}

  /// VTX power level
  var power: SG2VtxPowerLevel {
    get {_power ?? .vtxPit}
    set {_power = newValue}
  }
  /// Returns true if `power` has been explicitly set.
  var hasPower: Bool {self._power != nil}
  /// Clears the value of `power`. Subsequent reads from it will return its default value.
  mutating func clearPower() {self._power = nil}

  /// true = RF on, false = pit mode
  var rfEnabled: Bool {
    get {_rfEnabled ?? false}
    set {_rfEnabled = newValue}
  }
  /// Returns true if `rfEnabled` has been explicitly set.
  var hasRfEnabled: Bool {self._rfEnabled != nil}
  /// Clears the value of `rfEnabled`. Subsequent reads from it will return its default value.
  mutating func clearRfEnabled() {self._rfEnabled = nil}

  /// true = start recording, false = stop
  var cameraRecord: Bool {
    get {_cameraRecord ?? false}
    set {_cameraRecord = newValue}
  }
  /// Returns true if `cameraRecord` has been explicitly set.
  var hasCameraRecord: Bool {self._cameraRecord != nil}
  /// Clears the value of `cameraRecord`. Subsequent reads from it will return its default value.
  mutating func clearCameraRecord() {self._cameraRecord = nil}

  /// ask the device to emit a CameraConfig
  var requestStatus: Bool {
    get {_requestStatus ?? false}
    set {_requestStatus = newValue}
  }
  /// Returns true if `requestStatus` has been explicitly set.
  var hasRequestStatus: Bool {self._requestStatus != nil}
  /// Clears the value of `requestStatus`. Subsequent reads from it will return its default value.
  mutating func clearRequestStatus() {self._requestStatus = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _band: SG2VtxBand? = nil
  fileprivate var _channel: UInt32? = nil
  fileprivate var _freqMhz: UInt32? = nil
  fileprivate var _power: SG2VtxPowerLevel? = nil
  fileprivate var _rfEnabled: Bool? = nil
  fileprivate var _cameraRecord: Bool? = nil
  fileprivate var _requestStatus: Bool? = nil
}

/// Camera -> phone. Current device configuration / status snapshot.
nonisolated struct SG2CameraConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var band: SG2VtxBand = .a

  /// 1..8, 0 if frequency is not on a known channel
  var channel: UInt32 = 0

  var freqMhz: UInt32 = 0

  /// configured power level
  var power: SG2VtxPowerLevel = .vtxPit

  /// measured output power (from VTX 'v' response)
  var actualPowerMw: UInt32 = 0

  /// false = pit mode
  var rfEnabled: Bool = false

  var cameraRecording: Bool = false

  var flightState: SG2FlightState = .fsUnknown

  var altitudeAglM: Float = 0

  /// last VTX query returned a valid response
  var vtxResponsive: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Acknowledgement for a received command (folded into the STATUS notify path).
nonisolated struct SG2CommandAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var seq: UInt32 = 0

  var ok: Bool = false

  var message: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2GpsData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var lat: Double = 0

  var lon: Double = 0

  var altM: Double = 0

  var numSats: UInt32 = 0

  var fixType: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2ImuData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var accelX: Float = 0

  var accelY: Float = 0

  var accelZ: Float = 0

  var gyroX: Float = 0

  var gyroY: Float = 0

  var gyroZ: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2BaroData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var pressurePa: Float = 0

  var temperatureC: Float = 0

  var altitudeM: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2FlightStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var state: SG2FlightState = .fsUnknown

  var altitudeAglM: Float = 0

  var climbMs: Float = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2Health: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var batteryV: Float = 0

  var temperatureC: Float = 0

  var errorFlags: UInt32 = 0

  var uptimeS: UInt32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

nonisolated struct SG2Envelope: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var nodeSrc: SG2NodeId = .nodeUndefined

  var nodeDst: SG2NodeId = .nodeUndefined

  /// per-sender sequence number, wraps at 2^32
  var seq: UInt32 = 0

  /// sender time since boot in milliseconds
  var timestampMs: UInt64 = 0

  var payload: SG2Envelope.OneOf_Payload? = nil

  /// Camera / VTX control
  var camCommand: SG2CameraCommand {
    get {
      if case .camCommand(let v)? = payload {return v}
      return SG2CameraCommand()
    }
    set {payload = .camCommand(newValue)}
  }

  var camConfig: SG2CameraConfig {
    get {
      if case .camConfig(let v)? = payload {return v}
      return SG2CameraConfig()
    }
    set {payload = .camConfig(newValue)}
  }

  var ack: SG2CommandAck {
    get {
      if case .ack(let v)? = payload {return v}
      return SG2CommandAck()
    }
    set {payload = .ack(newValue)}
  }

  /// Telemetry (skeleton)
  var gps: SG2GpsData {
    get {
      if case .gps(let v)? = payload {return v}
      return SG2GpsData()
    }
    set {payload = .gps(newValue)}
  }

  var imu: SG2ImuData {
    get {
      if case .imu(let v)? = payload {return v}
      return SG2ImuData()
    }
    set {payload = .imu(newValue)}
  }

  var baro: SG2BaroData {
    get {
      if case .baro(let v)? = payload {return v}
      return SG2BaroData()
    }
    set {payload = .baro(newValue)}
  }

  var flight: SG2FlightStatus {
    get {
      if case .flight(let v)? = payload {return v}
      return SG2FlightStatus()
    }
    set {payload = .flight(newValue)}
  }

  var health: SG2Health {
    get {
      if case .health(let v)? = payload {return v}
      return SG2Health()
    }
    set {payload = .health(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  nonisolated enum OneOf_Payload: Equatable, Sendable {
    /// Camera / VTX control
    case camCommand(SG2CameraCommand)
    case camConfig(SG2CameraConfig)
    case ack(SG2CommandAck)
    /// Telemetry (skeleton)
    case gps(SG2GpsData)
    case imu(SG2ImuData)
    case baro(SG2BaroData)
    case flight(SG2FlightStatus)
    case health(SG2Health)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "sigma2"

nonisolated extension SG2NodeId: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NODE_UNDEFINED\0\u{1}NODE_NOSE_CONE\0\u{1}NODE_PAYLOAD\0\u{1}NODE_EBAY\0\u{1}NODE_ADS\0\u{1}NODE_ANTENNA_TRACKER\0\u{1}NODE_STATIONARY_GS\0\u{1}NODE_MOBILE_NODE1\0\u{1}NODE_MOBILE_NODE2\0\u{1}NODE_MOBILE_NODE3\0\u{1}NODE_MOBILE_NODE4\0\u{1}NODE_ROCKET_CAM\0")
}

nonisolated extension SG2FlightState: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0FS_UNKNOWN\0\u{1}FS_PAD\0\u{1}FS_BOOST\0\u{1}FS_COAST\0\u{1}FS_APOGEE\0\u{1}FS_RECOVERY\0\u{1}FS_LANDED\0")
}

nonisolated extension SG2VtxBand: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VTX_BAND_A\0\u{1}VTX_BAND_B\0")
}

nonisolated extension SG2VtxPowerLevel: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0VTX_PIT\0\u{1}VTX_25MW\0\u{1}VTX_200MW\0\u{1}VTX_1000MW\0\u{1}VTX_4000MW\0")
}

nonisolated extension SG2CameraCommand: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CameraCommand"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}band\0\u{1}channel\0\u{3}freq_mhz\0\u{1}power\0\u{3}rf_enabled\0\u{3}camera_record\0\u{3}request_status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self._band) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self._channel) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self._freqMhz) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self._power) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._rfEnabled) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._cameraRecord) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._requestStatus) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._band {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._channel {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._freqMhz {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._power {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._rfEnabled {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._cameraRecord {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._requestStatus {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2CameraCommand, rhs: SG2CameraCommand) -> Bool {
    if lhs._band != rhs._band {return false}
    if lhs._channel != rhs._channel {return false}
    if lhs._freqMhz != rhs._freqMhz {return false}
    if lhs._power != rhs._power {return false}
    if lhs._rfEnabled != rhs._rfEnabled {return false}
    if lhs._cameraRecord != rhs._cameraRecord {return false}
    if lhs._requestStatus != rhs._requestStatus {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2CameraConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CameraConfig"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}band\0\u{1}channel\0\u{3}freq_mhz\0\u{1}power\0\u{3}actual_power_mw\0\u{3}rf_enabled\0\u{3}camera_recording\0\u{3}flight_state\0\u{3}altitude_agl_m\0\u{3}vtx_responsive\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.band) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.channel) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.freqMhz) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.power) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.actualPowerMw) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.rfEnabled) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.cameraRecording) }()
      case 8: try { try decoder.decodeSingularEnumField(value: &self.flightState) }()
      case 9: try { try decoder.decodeSingularFloatField(value: &self.altitudeAglM) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self.vtxResponsive) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.band != .a {
      try visitor.visitSingularEnumField(value: self.band, fieldNumber: 1)
    }
    if self.channel != 0 {
      try visitor.visitSingularUInt32Field(value: self.channel, fieldNumber: 2)
    }
    if self.freqMhz != 0 {
      try visitor.visitSingularUInt32Field(value: self.freqMhz, fieldNumber: 3)
    }
    if self.power != .vtxPit {
      try visitor.visitSingularEnumField(value: self.power, fieldNumber: 4)
    }
    if self.actualPowerMw != 0 {
      try visitor.visitSingularUInt32Field(value: self.actualPowerMw, fieldNumber: 5)
    }
    if self.rfEnabled != false {
      try visitor.visitSingularBoolField(value: self.rfEnabled, fieldNumber: 6)
    }
    if self.cameraRecording != false {
      try visitor.visitSingularBoolField(value: self.cameraRecording, fieldNumber: 7)
    }
    if self.flightState != .fsUnknown {
      try visitor.visitSingularEnumField(value: self.flightState, fieldNumber: 8)
    }
    if self.altitudeAglM.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.altitudeAglM, fieldNumber: 9)
    }
    if self.vtxResponsive != false {
      try visitor.visitSingularBoolField(value: self.vtxResponsive, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2CameraConfig, rhs: SG2CameraConfig) -> Bool {
    if lhs.band != rhs.band {return false}
    if lhs.channel != rhs.channel {return false}
    if lhs.freqMhz != rhs.freqMhz {return false}
    if lhs.power != rhs.power {return false}
    if lhs.actualPowerMw != rhs.actualPowerMw {return false}
    if lhs.rfEnabled != rhs.rfEnabled {return false}
    if lhs.cameraRecording != rhs.cameraRecording {return false}
    if lhs.flightState != rhs.flightState {return false}
    if lhs.altitudeAglM != rhs.altitudeAglM {return false}
    if lhs.vtxResponsive != rhs.vtxResponsive {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2CommandAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CommandAck"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}seq\0\u{1}ok\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.ok) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 1)
    }
    if self.ok != false {
      try visitor.visitSingularBoolField(value: self.ok, fieldNumber: 2)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2CommandAck, rhs: SG2CommandAck) -> Bool {
    if lhs.seq != rhs.seq {return false}
    if lhs.ok != rhs.ok {return false}
    if lhs.message != rhs.message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2GpsData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GpsData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}lat\0\u{1}lon\0\u{3}alt_m\0\u{3}num_sats\0\u{3}fix_type\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.lat) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.lon) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.altM) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.numSats) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.fixType) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.lat.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.lat, fieldNumber: 1)
    }
    if self.lon.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.lon, fieldNumber: 2)
    }
    if self.altM.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.altM, fieldNumber: 3)
    }
    if self.numSats != 0 {
      try visitor.visitSingularUInt32Field(value: self.numSats, fieldNumber: 4)
    }
    if self.fixType != 0 {
      try visitor.visitSingularUInt32Field(value: self.fixType, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2GpsData, rhs: SG2GpsData) -> Bool {
    if lhs.lat != rhs.lat {return false}
    if lhs.lon != rhs.lon {return false}
    if lhs.altM != rhs.altM {return false}
    if lhs.numSats != rhs.numSats {return false}
    if lhs.fixType != rhs.fixType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2ImuData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ImuData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}accel_x\0\u{3}accel_y\0\u{3}accel_z\0\u{3}gyro_x\0\u{3}gyro_y\0\u{3}gyro_z\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.accelX) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.accelY) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.accelZ) }()
      case 4: try { try decoder.decodeSingularFloatField(value: &self.gyroX) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self.gyroY) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.gyroZ) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accelX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.accelX, fieldNumber: 1)
    }
    if self.accelY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.accelY, fieldNumber: 2)
    }
    if self.accelZ.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.accelZ, fieldNumber: 3)
    }
    if self.gyroX.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gyroX, fieldNumber: 4)
    }
    if self.gyroY.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gyroY, fieldNumber: 5)
    }
    if self.gyroZ.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.gyroZ, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2ImuData, rhs: SG2ImuData) -> Bool {
    if lhs.accelX != rhs.accelX {return false}
    if lhs.accelY != rhs.accelY {return false}
    if lhs.accelZ != rhs.accelZ {return false}
    if lhs.gyroX != rhs.gyroX {return false}
    if lhs.gyroY != rhs.gyroY {return false}
    if lhs.gyroZ != rhs.gyroZ {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2BaroData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BaroData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pressure_pa\0\u{3}temperature_c\0\u{3}altitude_m\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.pressurePa) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.temperatureC) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.altitudeM) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.pressurePa.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.pressurePa, fieldNumber: 1)
    }
    if self.temperatureC.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperatureC, fieldNumber: 2)
    }
    if self.altitudeM.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.altitudeM, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2BaroData, rhs: SG2BaroData) -> Bool {
    if lhs.pressurePa != rhs.pressurePa {return false}
    if lhs.temperatureC != rhs.temperatureC {return false}
    if lhs.altitudeM != rhs.altitudeM {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2FlightStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FlightStatus"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}state\0\u{3}altitude_agl_m\0\u{3}climb_ms\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.altitudeAglM) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.climbMs) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.state != .fsUnknown {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 1)
    }
    if self.altitudeAglM.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.altitudeAglM, fieldNumber: 2)
    }
    if self.climbMs.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.climbMs, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2FlightStatus, rhs: SG2FlightStatus) -> Bool {
    if lhs.state != rhs.state {return false}
    if lhs.altitudeAglM != rhs.altitudeAglM {return false}
    if lhs.climbMs != rhs.climbMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2Health: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Health"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}battery_v\0\u{3}temperature_c\0\u{3}error_flags\0\u{3}uptime_s\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.batteryV) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.temperatureC) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.errorFlags) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.uptimeS) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.batteryV.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.batteryV, fieldNumber: 1)
    }
    if self.temperatureC.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.temperatureC, fieldNumber: 2)
    }
    if self.errorFlags != 0 {
      try visitor.visitSingularUInt32Field(value: self.errorFlags, fieldNumber: 3)
    }
    if self.uptimeS != 0 {
      try visitor.visitSingularUInt32Field(value: self.uptimeS, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2Health, rhs: SG2Health) -> Bool {
    if lhs.batteryV != rhs.batteryV {return false}
    if lhs.temperatureC != rhs.temperatureC {return false}
    if lhs.errorFlags != rhs.errorFlags {return false}
    if lhs.uptimeS != rhs.uptimeS {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension SG2Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Envelope"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}node_src\0\u{3}node_dst\0\u{1}seq\0\u{3}timestamp_ms\0\u{4}\u{6}cam_command\0\u{3}cam_config\0\u{1}ack\0\u{2}\u{8}gps\0\u{1}imu\0\u{1}baro\0\u{1}flight\0\u{1}health\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.nodeSrc) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.nodeDst) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.seq) }()
      case 4: try { try decoder.decodeSingularUInt64Field(value: &self.timestampMs) }()
      case 10: try {
        var v: SG2CameraCommand?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .camCommand(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .camCommand(v)
        }
      }()
      case 11: try {
        var v: SG2CameraConfig?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .camConfig(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .camConfig(v)
        }
      }()
      case 12: try {
        var v: SG2CommandAck?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .ack(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .ack(v)
        }
      }()
      case 20: try {
        var v: SG2GpsData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .gps(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .gps(v)
        }
      }()
      case 21: try {
        var v: SG2ImuData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .imu(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .imu(v)
        }
      }()
      case 22: try {
        var v: SG2BaroData?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .baro(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .baro(v)
        }
      }()
      case 23: try {
        var v: SG2FlightStatus?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .flight(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .flight(v)
        }
      }()
      case 24: try {
        var v: SG2Health?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .health(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .health(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.nodeSrc != .nodeUndefined {
      try visitor.visitSingularEnumField(value: self.nodeSrc, fieldNumber: 1)
    }
    if self.nodeDst != .nodeUndefined {
      try visitor.visitSingularEnumField(value: self.nodeDst, fieldNumber: 2)
    }
    if self.seq != 0 {
      try visitor.visitSingularUInt32Field(value: self.seq, fieldNumber: 3)
    }
    if self.timestampMs != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestampMs, fieldNumber: 4)
    }
    switch self.payload {
    case .camCommand?: try {
      guard case .camCommand(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    }()
    case .camConfig?: try {
      guard case .camConfig(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .ack?: try {
      guard case .ack(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case .gps?: try {
      guard case .gps(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
    }()
    case .imu?: try {
      guard case .imu(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
    }()
    case .baro?: try {
      guard case .baro(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 22)
    }()
    case .flight?: try {
      guard case .flight(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 23)
    }()
    case .health?: try {
      guard case .health(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 24)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: SG2Envelope, rhs: SG2Envelope) -> Bool {
    if lhs.nodeSrc != rhs.nodeSrc {return false}
    if lhs.nodeDst != rhs.nodeDst {return false}
    if lhs.seq != rhs.seq {return false}
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
